<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Davivienda.Framework.Lib.VoucherNumber" Version="1.0.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.5" />
      <PackageReference Include="CData.Sybase" Version="22.0.8389" />
      <PackageReference Include="Davivienda.Framework.Lib.Crypto" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SendSPFT.CrossCutting\SendSPFT.CrossCutting.csproj" />
    <ProjectReference Include="..\SendSPFT.DataAccess.Contracts\SendSPFT.DataAccess.Contracts.csproj" />
  </ItemGroup>

</Project>

