{
 "title": "Sri Facturacion",
 "tags": [ "sri" ],
 "panels": [
  {
   "title": "Facturas procesadas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(sri_facturas_procesadas_total)"
    }
   ]
  },
  {
   "title": "Errores",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "sum(sri_errores_total)" }
   ]
  },
  {
   "title": "Requests HTTP por segundo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_received_total[5m])"
    }
   ]
  }
 ]
}