sonar.projectKey=Internal.App.Worker.SendSPFT
sonar.working.directory=D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Test\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=D:\\TV
sonar.pullrequest.cache.basepath=D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Test

50DAD375-FDA8-450D-A473-D44F104FC42B.sonar.projectKey=Internal.App.Worker.SendSPFT:50DAD375-FDA8-450D-A473-D44F104FC42B
50DAD375-FDA8-450D-A473-D44F104FC42B.sonar.projectName=SendSPFT.Business
50DAD375-FDA8-450D-A473-D44F104FC42B.sonar.projectBaseDir=D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Business
50DAD375-FDA8-450D-A473-D44F104FC42B.sonar.sourceEncoding=utf-8
50DAD375-FDA8-450D-A473-D44F104FC42B.sonar.sources=\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Business\\Models\\ApiQCD\\Actividad.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Business\\Models\\ApiQCD\\Cliente.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Business\\Models\\ApiQCD\\ClienteAC.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Business\\Models\\ApiQCD\\Direccion.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Business\\Models\\ApiQCD\\InfoFiscal.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Business\\Models\\ApiQCD\\Ingresos.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Business\\Models\\ApiQCD\\ReqConsulta.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Business\\Models\\ApiQCD\\Socio.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Business\\Models\\BD\\FileProcDigDto.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Business\\Models\\BD\\FileRegBitacoraDto.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Business\\Models\\BD\\GetDatesSyb12ResponseDto.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Business\\Models\\BD\\TdAttachmentDto.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Business\\Models\\EXT\\RequestResponse\\GetVirtualKeyRequest.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Business\\Models\\EXT\\RequestResponse\\GetVirtualKeyResponse.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Business\\Models\\INT\\RequestResponse\\PasswordChangeRequest.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Business\\Models\\INT\\RequestResponse\\PasswordChangeResponse.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Business\\Models\\RequestContextHeaders.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Business\\Models\\Retries\\PasswordChangeRetryPolicyRequest.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Business\\Models\\SFTP\\SftpSettings.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Business\\Models\\SFTP\\SftpUploadResult.cs"

50DAD375-FDA8-450D-A473-D44F104FC42B.sonar.cs.analyzer.projectOutPaths=\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Test\\.sonarqube\\out\\0"
50DAD375-FDA8-450D-A473-D44F104FC42B.sonar.cs.roslyn.reportFilePaths=\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Test\\.sonarqube\\out\\0\\Issues.json"

50DAD375-FDA8-450D-A473-D44F104FC42B.sonar.working.directory=D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Test\\.sonarqube\\out\\.sonar\\mod0
5435FEFA-21CD-4E88-B720-878C5A4AC927.sonar.projectKey=Internal.App.Worker.SendSPFT:5435FEFA-21CD-4E88-B720-878C5A4AC927
5435FEFA-21CD-4E88-B720-878C5A4AC927.sonar.projectName=SendSPFT.DataAccess.Contracts
5435FEFA-21CD-4E88-B720-878C5A4AC927.sonar.projectBaseDir=D:\\TV\\temp\\Core.SET.Web.Api.GetHolidays\\Core.SET.Web.Api.GetHolidays.DataAccess.Contracts
5435FEFA-21CD-4E88-B720-878C5A4AC927.sonar.sourceEncoding=utf-8
5435FEFA-21CD-4E88-B720-878C5A4AC927.sonar.sources=\
"D:\\TV\\temp\\Core.SET.Web.Api.GetHolidays\\Core.SET.Web.Api.GetHolidays.DataAccess.Contracts\\Context\\IBdSybase.cs",\
"D:\\TV\\temp\\Core.SET.Web.Api.GetHolidays\\Core.SET.Web.Api.GetHolidays.DataAccess.Contracts\\Context\\ISendSftpContext.cs",\
"D:\\TV\\temp\\Core.SET.Web.Api.GetHolidays\\Core.SET.Web.Api.GetHolidays.DataAccess.Contracts\\Exec\\Func\\ISelectRegistryBD.cs",\
"D:\\TV\\temp\\Core.SET.Web.Api.GetHolidays\\Core.SET.Web.Api.GetHolidays.DataAccess.Contracts\\Exec\\Func\\IUpdateTableBD.cs",\
"D:\\TV\\temp\\Core.SET.Web.Api.GetHolidays\\Core.SET.Web.Api.GetHolidays.DataAccess.Contracts\\Exec\\SP\\IFileProcDigExecSP.cs",\
"D:\\TV\\temp\\Core.SET.Web.Api.GetHolidays\\Core.SET.Web.Api.GetHolidays.DataAccess.Contracts\\Exec\\SP\\IFileRegBitacoraExexSP.cs",\
"D:\\TV\\temp\\Core.SET.Web.Api.GetHolidays\\Core.SET.Web.Api.GetHolidays.DataAccess.Contracts\\Exec\\SP\\IGetDatesSyb12.cs"

5435FEFA-21CD-4E88-B720-878C5A4AC927.sonar.cs.analyzer.projectOutPaths=\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Test\\.sonarqube\\out\\1"
5435FEFA-21CD-4E88-B720-878C5A4AC927.sonar.cs.roslyn.reportFilePaths=\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Test\\.sonarqube\\out\\1\\Issues.json"

5435FEFA-21CD-4E88-B720-878C5A4AC927.sonar.working.directory=D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Test\\.sonarqube\\out\\.sonar\\mod1
9ADAE446-DA17-469A-9096-0A4059ACC574.sonar.projectKey=Internal.App.Worker.SendSPFT:9ADAE446-DA17-469A-9096-0A4059ACC574
9ADAE446-DA17-469A-9096-0A4059ACC574.sonar.projectName=SendSPFT.Application.Contracts
9ADAE446-DA17-469A-9096-0A4059ACC574.sonar.projectBaseDir=D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Application.Contracts
9ADAE446-DA17-469A-9096-0A4059ACC574.sonar.sourceEncoding=utf-8
9ADAE446-DA17-469A-9096-0A4059ACC574.sonar.sources=\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Application.Contracts\\Clients\\IQueryCustomerDataClient.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Application.Contracts\\Clients\\ISftpFileUploader.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Application.Contracts\\DTOs\\ContratoFifo.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Application.Contracts\\DTOs\\RequestSnsDto.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Application.Contracts\\DTOs\\ResponseReintentos.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Application.Contracts\\Services\\ISendSPFTService.cs"

9ADAE446-DA17-469A-9096-0A4059ACC574.sonar.cs.analyzer.projectOutPaths=\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Test\\.sonarqube\\out\\2"
9ADAE446-DA17-469A-9096-0A4059ACC574.sonar.cs.roslyn.reportFilePaths=\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Test\\.sonarqube\\out\\2\\Issues.json"

9ADAE446-DA17-469A-9096-0A4059ACC574.sonar.working.directory=D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Test\\.sonarqube\\out\\.sonar\\mod2
2EF44EC4-78D9-4569-8585-7E2926D5D1DB.sonar.projectKey=Internal.App.Worker.SendSPFT:2EF44EC4-78D9-4569-8585-7E2926D5D1DB
2EF44EC4-78D9-4569-8585-7E2926D5D1DB.sonar.projectName=SendSPFT.DataAccess.Contracts
2EF44EC4-78D9-4569-8585-7E2926D5D1DB.sonar.projectBaseDir=D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.DataAccess.Contracts
2EF44EC4-78D9-4569-8585-7E2926D5D1DB.sonar.sourceEncoding=utf-8
2EF44EC4-78D9-4569-8585-7E2926D5D1DB.sonar.sources=\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.DataAccess.Contracts\\Context\\IBdSybase.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.DataAccess.Contracts\\Context\\ISendSftpContext.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.DataAccess.Contracts\\Exec\\Func\\ISelectRegistryBD.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.DataAccess.Contracts\\Exec\\Func\\IUpdateTableBD.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.DataAccess.Contracts\\Exec\\SP\\IFileProcDigExecSP.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.DataAccess.Contracts\\Exec\\SP\\IGetDatesSyb12.cs"

2EF44EC4-78D9-4569-8585-7E2926D5D1DB.sonar.cs.analyzer.projectOutPaths=\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Test\\.sonarqube\\out\\3"
2EF44EC4-78D9-4569-8585-7E2926D5D1DB.sonar.cs.roslyn.reportFilePaths=\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Test\\.sonarqube\\out\\3\\Issues.json"

2EF44EC4-78D9-4569-8585-7E2926D5D1DB.sonar.working.directory=D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Test\\.sonarqube\\out\\.sonar\\mod3
25A10BAB-E22E-40AE-B239-CBBC24F154D9.sonar.projectKey=Internal.App.Worker.SendSPFT:25A10BAB-E22E-40AE-B239-CBBC24F154D9
25A10BAB-E22E-40AE-B239-CBBC24F154D9.sonar.projectName=SendSPFT.DataAccess
25A10BAB-E22E-40AE-B239-CBBC24F154D9.sonar.projectBaseDir=D:\\TV\\temp\\Core.SET.Web.Api.GetHolidays\\Core.SET.Web.Api.GetHolidays.DataAccess
25A10BAB-E22E-40AE-B239-CBBC24F154D9.sonar.sourceEncoding=utf-8
25A10BAB-E22E-40AE-B239-CBBC24F154D9.sonar.sources=\
"D:\\TV\\temp\\Core.SET.Web.Api.GetHolidays\\Core.SET.Web.Api.GetHolidays.DataAccess\\Context\\BdSybase.cs",\
"D:\\TV\\temp\\Core.SET.Web.Api.GetHolidays\\Core.SET.Web.Api.GetHolidays.DataAccess\\Context\\DataBase.cs",\
"D:\\TV\\temp\\Core.SET.Web.Api.GetHolidays\\Core.SET.Web.Api.GetHolidays.DataAccess\\Context\\SendSftpContext.cs",\
"D:\\TV\\temp\\Core.SET.Web.Api.GetHolidays\\Core.SET.Web.Api.GetHolidays.DataAccess\\Exec\\Func\\SelectRegistryBD.cs",\
"D:\\TV\\temp\\Core.SET.Web.Api.GetHolidays\\Core.SET.Web.Api.GetHolidays.DataAccess\\Exec\\Func\\UpdateTableBD.cs",\
"D:\\TV\\temp\\Core.SET.Web.Api.GetHolidays\\Core.SET.Web.Api.GetHolidays.DataAccess\\Exec\\SP\\FileProcDigExecSP.cs",\
"D:\\TV\\temp\\Core.SET.Web.Api.GetHolidays\\Core.SET.Web.Api.GetHolidays.DataAccess\\Exec\\SP\\FileRegBitacoraExexSP.cs",\
"D:\\TV\\temp\\Core.SET.Web.Api.GetHolidays\\Core.SET.Web.Api.GetHolidays.DataAccess\\Exec\\SP\\GetDatesSyb12.cs"

25A10BAB-E22E-40AE-B239-CBBC24F154D9.sonar.cs.analyzer.projectOutPaths=\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Test\\.sonarqube\\out\\4"
25A10BAB-E22E-40AE-B239-CBBC24F154D9.sonar.cs.roslyn.reportFilePaths=\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Test\\.sonarqube\\out\\4\\Issues.json"

25A10BAB-E22E-40AE-B239-CBBC24F154D9.sonar.working.directory=D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Test\\.sonarqube\\out\\.sonar\\mod4
05681D75-D6FB-44AC-B32F-626F103D111E.sonar.projectKey=Internal.App.Worker.SendSPFT:05681D75-D6FB-44AC-B32F-626F103D111E
05681D75-D6FB-44AC-B32F-626F103D111E.sonar.projectName=SendSPFT.CrossCutting
05681D75-D6FB-44AC-B32F-626F103D111E.sonar.projectBaseDir=D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.CrossCutting
05681D75-D6FB-44AC-B32F-626F103D111E.sonar.sourceEncoding=utf-8
05681D75-D6FB-44AC-B32F-626F103D111E.sonar.sources=\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.CrossCutting\\Config\\AppConfiguration.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.CrossCutting\\Config\\HealthCheckConfig.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.CrossCutting\\Healthchecks\\HttpEndpointHealthCheck.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.CrossCutting\\Helpers\\Contracts\\IRequestContextExtractor.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.CrossCutting\\Helpers\\Contracts\\IRequestLogger.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.CrossCutting\\Helpers\\Contracts\\IServiceResponseFactory.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.CrossCutting\\Helpers\\RequestContextExtractor.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.CrossCutting\\Helpers\\RequestLogger.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.CrossCutting\\Helpers\\ServiceResponseFactory.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.CrossCutting\\Helpers\\SwaggerHeaderFilter.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.CrossCutting\\Mapper\\AttachmentMapper.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.CrossCutting\\Mapper\\IAttachmentMapper.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.CrossCutting\\Metrics\\MetricCollector.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.CrossCutting\\Models\\HealthCheckModels\\HealthCheckResponse.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.CrossCutting\\Models\\HealthCheckModels\\IndividualHealthCheckResponse.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.CrossCutting\\Subservices\\FileProcessingService.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.CrossCutting\\Subservices\\IFileProcessingService.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.CrossCutting\\Subservices\\IProcessRecord.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.CrossCutting\\Subservices\\ProcessRecord.cs"

05681D75-D6FB-44AC-B32F-626F103D111E.sonar.cs.analyzer.projectOutPaths=\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Test\\.sonarqube\\out\\5"
05681D75-D6FB-44AC-B32F-626F103D111E.sonar.cs.roslyn.reportFilePaths=\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Test\\.sonarqube\\out\\5\\Issues.json"

05681D75-D6FB-44AC-B32F-626F103D111E.sonar.working.directory=D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Test\\.sonarqube\\out\\.sonar\\mod5
92EC34B0-EE2B-468D-94B3-A118557B875C.sonar.projectKey=Internal.App.Worker.SendSPFT:92EC34B0-EE2B-468D-94B3-A118557B875C
92EC34B0-EE2B-468D-94B3-A118557B875C.sonar.projectName=SendSPFT.Application
92EC34B0-EE2B-468D-94B3-A118557B875C.sonar.projectBaseDir=D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Application
92EC34B0-EE2B-468D-94B3-A118557B875C.sonar.sourceEncoding=utf-8
92EC34B0-EE2B-468D-94B3-A118557B875C.sonar.sources=\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Application\\Clients\\QueryCustomerDataClient.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Application\\Clients\\SftpFileUploaderClient.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Application\\Services\\SendSftpService.cs"

92EC34B0-EE2B-468D-94B3-A118557B875C.sonar.cs.analyzer.projectOutPaths=\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Test\\.sonarqube\\out\\6"
92EC34B0-EE2B-468D-94B3-A118557B875C.sonar.cs.roslyn.reportFilePaths=\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Test\\.sonarqube\\out\\6\\Issues.json"

92EC34B0-EE2B-468D-94B3-A118557B875C.sonar.working.directory=D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Test\\.sonarqube\\out\\.sonar\\mod6
FF804F46-CF5A-4E97-88B1-67BFE6AED464.sonar.projectKey=Internal.App.Worker.SendSPFT:FF804F46-CF5A-4E97-88B1-67BFE6AED464
FF804F46-CF5A-4E97-88B1-67BFE6AED464.sonar.projectName=SendSPFT.DataAccess
FF804F46-CF5A-4E97-88B1-67BFE6AED464.sonar.projectBaseDir=D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.DataAccess
FF804F46-CF5A-4E97-88B1-67BFE6AED464.sonar.sourceEncoding=utf-8
FF804F46-CF5A-4E97-88B1-67BFE6AED464.sonar.sources=\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.DataAccess\\Context\\BdSybase.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.DataAccess\\Context\\SendSftpContext.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.DataAccess\\Exec\\Func\\SelectRegistryBD.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.DataAccess\\Exec\\Func\\UpdateTableBD.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.DataAccess\\Exec\\SP\\FileProcDigExecSP.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.DataAccess\\Exec\\SP\\GetDatesSyb12.cs"

FF804F46-CF5A-4E97-88B1-67BFE6AED464.sonar.cs.analyzer.projectOutPaths=\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Test\\.sonarqube\\out\\7"
FF804F46-CF5A-4E97-88B1-67BFE6AED464.sonar.cs.roslyn.reportFilePaths=\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Test\\.sonarqube\\out\\7\\Issues.json"

FF804F46-CF5A-4E97-88B1-67BFE6AED464.sonar.working.directory=D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Test\\.sonarqube\\out\\.sonar\\mod7
8FB8FF17-626F-4ACD-844E-2ECCDFF570B6.sonar.projectKey=Internal.App.Worker.SendSPFT:8FB8FF17-626F-4ACD-844E-2ECCDFF570B6
8FB8FF17-626F-4ACD-844E-2ECCDFF570B6.sonar.projectName=SendSPFT.Test
8FB8FF17-626F-4ACD-844E-2ECCDFF570B6.sonar.projectBaseDir=D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Test
8FB8FF17-626F-4ACD-844E-2ECCDFF570B6.sonar.sourceEncoding=utf-8
8FB8FF17-626F-4ACD-844E-2ECCDFF570B6.sonar.sources=
8FB8FF17-626F-4ACD-844E-2ECCDFF570B6.sonar.tests=\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Test\\CrossCuttingHelpersTests.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Test\\RecordTest.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Test\\SendSftpServiceTests.cs",\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Test\\Run-SonarAnalysis.ps1"

8FB8FF17-626F-4ACD-844E-2ECCDFF570B6.sonar.cs.analyzer.projectOutPaths=\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Test\\.sonarqube\\out\\8"
8FB8FF17-626F-4ACD-844E-2ECCDFF570B6.sonar.cs.roslyn.reportFilePaths=\
"D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Test\\.sonarqube\\out\\8\\Issues.json"

8FB8FF17-626F-4ACD-844E-2ECCDFF570B6.sonar.working.directory=D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\SendSPFT.Test\\.sonarqube\\out\\.sonar\\mod8
sonar.host.url=http://crsjce010275vm:9000
sonar.cs.opencover.reportsPaths=D:\\TV\\LF\\git\\Internal.App.Worker.SendSPFT\\TestResults\\coverage.opencover.xml
sonar.exclusions=**/temp/**,**/bin/**,**/obj/**
sonar.cpd.exclusions=**/temp/**,**/bin/**,**/obj/**
sonar.visualstudio.enable=false

sonar.modules=50DAD375-FDA8-450D-A473-D44F104FC42B,5435FEFA-21CD-4E88-B720-878C5A4AC927,9ADAE446-DA17-469A-9096-0A4059ACC574,2EF44EC4-78D9-4569-8585-7E2926D5D1DB,25A10BAB-E22E-40AE-B239-CBBC24F154D9,05681D75-D6FB-44AC-B32F-626F103D111E,92EC34B0-EE2B-468D-94B3-A118557B875C,FF804F46-CF5A-4E97-88B1-67BFE6AED464,8FB8FF17-626F-4ACD-844E-2ECCDFF570B6

