FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore temp/3162026/ramal-DEV/src/AuthBackend.Gateway/AuthBackend.Gateway.csproj
RUN dotnet publish temp/3162026/ramal-DEV/src/AuthBackend.Gateway/AuthBackend.Gateway.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 8081
ENTRYPOINT ["dotnet", "AuthBackend.Gateway.dll"]
